# Generated by Django 3.1.4 on 2020-12-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_order_orderproduct_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='image',
            field=models.FileField(default='noimage.jpg', null=True, upload_to=''),
        ),
    ]
