# Generated by Django 3.1.4 on 2020-12-18 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_todo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='image',
        ),
    ]
